In [119]:
import pandas as pd
import numpy as np
import json

## Define the metadata

In [120]:
organism = "homo_sapiens"
cell_source = "adipose"
cell_state = None

reference = "GRCh38"
paper_doi = "https://www.nature.com/articles/s41467-023-36983-2#Sec34"
table_link = "https://static-content.springer.com/esm/art%3A10.1038%2Fs41590-021-00922-4/MediaObjects/41590_2021_922_MOESM2_ESM.xlsx"

# don't include in header
table_name = "41467_2023_36983_MOESM4_ESM.xlsx"
table_name = "paper_degs.xlsx" # local name

## Read in file

In [121]:
excel = pd.read_excel(table_name, skiprows = 0, sheet_name=["17_Angueira et al."])

df = pd.concat(excel.values())
ctmap = pd.read_csv("ctmap/ctmap_angueira.txt", sep="\t", header=None, names=["ctnum", "ctname"], index_col=0)
df["cluster_name"] = df["cluster"].map(ctmap["ctname"])

df

,gene,p_val,avg_log2FC,pct.1,pct.2,p_val_adj,cluster,cluster_name
0,EEF1A1,4.024568e-206,0.660106,0.745,0.551,1.194129e-201,0,Adipocyte
1,IGHG3,3.443877e-38,0.430059,0.169,0.097,1.021833e-33,0,Adipocyte
2,FABP4,1.217300e-110,0.414764,0.844,0.586,3.611851e-106,0,Adipocyte
3,B2M,6.344955e-24,0.386782,0.434,0.434,1.882612e-19,0,Adipocyte
4,FTL,1.086667e-18,0.364124,0.254,0.210,3.224249e-14,0,Adipocyte
...,...,...,...,...,...,...,...,...
46173,ARL15,8.855273e-01,-0.379113,0.759,0.702,1.000000e+00,23,smooth muscle
46174,ANO6,9.737803e-01,-0.180530,0.777,0.666,1.000000e+00,23,smooth muscle
46175,PID1,9.791153e-01,-0.218497,0.402,0.384,1.000000e+00,23,smooth muscle
46176,MYO5A,9.924217e-01,-0.176698,0.348,0.322,1.000000e+00,23,smooth muscle
46177,DLC1,9.981807e-01,-0.214687,0.946,0.829,1.000000e+00,23,smooth muscle

In [122]:
df.head()

,gene,p_val,avg_log2FC,pct.1,pct.2,p_val_adj,cluster,cluster_name
0,EEF1A1,4.024568e-206,0.660106,0.745,0.551,1.194129e-201,0,Adipocyte
1,IGHG3,3.443877e-38,0.430059,0.169,0.097,1.021833e-33,0,Adipocyte
2,FABP4,1.217300e-110,0.414764,0.844,0.586,3.611851e-106,0,Adipocyte
3,B2M,6.344955e-24,0.386782,0.434,0.434,1.882612e-19,0,Adipocyte
4,FTL,1.086667e-18,0.364124,0.254,0.210,3.224249e-14,0,Adipocyte

## Unfiltered

In [123]:
unfiltered_df = df.copy()
unfiltered_df.rename(columns ={"cluster_name": "cell_type_label", "gene": "feature_name"}, inplace=True)
unfiltered_df["organism"] = organism
unfiltered_df["cell_source"] = cell_source
unfiltered_df["cell_state"] = cell_state
unfiltered_df["feature_identifier"] = None

unfiltered_df.drop(['p_val', 'avg_log2FC', 'pct.1', 'pct.2', 'p_val_adj'], axis=1, inplace=True) 
result = [] 

for _, row in unfiltered_df.iterrows():
    result.append({"extracted": {"organism": row["organism"], "cell_type_label": row["cell_type_label"], "cell_source": row["cell_source"], "cell_state": row["cell_state"], "feature_name": row["feature_name"], "feature_type": "gene"},
                   "derived": {"organism": row["organism"], "cell_type_id": None, "cell_type_label": row["cell_type_label"], "cell_source": row["cell_source"], "cell_state": row["cell_state"], "feature_name": row["feature_name"], "feature_type": "gene", "feature_identifier": row["feature_identifier"], "feature_type": "ensembl"},
                   "source": {"source_type": "deg", "source_rationale": "unfiltered", "source_id": "deg"}})

result

[{'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'EEF1A1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'EEF1A1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHG3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHG3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FABP4',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FABP4',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'B2M',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'B2M',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FTL',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FTL',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FOS',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FOS',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ACTB',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ACTB',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGKC',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGKC',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AHNAK',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AHNAK',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TPT1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TPT1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB4X',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB4X',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MGP',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MGP',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHGP',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHGP',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHA1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'IGHA1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PLIN1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PLIN1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CCDC80',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CCDC80',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FTH1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FTH1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SNHG25',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SNHG25',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TXNIP',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TXNIP',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ATP5F1E',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ATP5F1E',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AL627171.2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AL627171.2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PLCG2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PLCG2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB10',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB10',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ITLN1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ITLN1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SCD',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SCD',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'VIM',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'VIM',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MYL6',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MYL6',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LENG8',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LENG8',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'UBA52',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'UBA52',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FP236383.3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FP236383.3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'DCN',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'DCN',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SAA1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SAA1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ADH1B',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ADH1B',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'EEF2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'EEF2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FBXL17',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FBXL17',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LGALS1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LGALS1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GPX4',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GPX4',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'unfiltered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GSN',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GSN',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',

In [124]:
with open('evidence_unfiltered_angueira.json', 'w') as f:
    json.dump(result, f, indent = 4)

## Perform the filtering

In [125]:
col_pval = "p_val_adj"
col_lfc = "avg_log2FC"
col_gene = "gene"
col_ct = "cluster_name" # says cluster in table, but before this had "celltype"
col_rank = "pct.1" # set to None if pct. 1DNE

In [126]:
min_mean = 100
max_pval = 1e-10
min_lfc = 2.2
max_gene_shares = 2
max_per_celltype = 20

# filter by pval and lfc
dfc = df.query(f"{col_pval} <= {max_pval} & {col_lfc} >= {min_lfc}")

# mask out genes that are shared between max_gene_shares cell types
non_repeat_genes = dfc[col_gene].value_counts()[dfc[col_gene].value_counts() < max_gene_shares].index.values

m = dfc[dfc[col_gene].isin(non_repeat_genes)]

if col_rank:
    m = m.sort_values(col_rank, ascending = True)

# max number to sample is equal to the min number of genes across all celltype
n_sample = min(m[col_ct].value_counts().max(), max_per_celltype)

# sample n_sample genes
markers = m.groupby(col_ct).tail(n_sample)
markers_dict = markers.groupby(col_ct)[col_gene].apply(lambda x: list(x)).to_dict()

## Check how many genes per cell type

In [127]:
markers

,gene,p_val,avg_log2FC,pct.1,pct.2,p_val_adj,cluster,cluster_name
30518,NKAIN2,1.624020e-203,2.494707,0.370,0.063,4.818629e-199,16,Endo
42728,ADGRL3,1.224136e-122,2.325794,0.556,0.075,3.632134e-118,22,smooth muscle
28795,FAM155A,0.000000e+00,2.204404,0.635,0.123,0.000000e+00,15,Endo
16612,AL357507.1,0.000000e+00,2.349605,0.663,0.080,0.000000e+00,8,Endo
44535,PCDH7,1.026978e-95,2.214234,0.679,0.107,3.047145e-91,23,smooth muscle
44539,KCNMA1,6.509471e-74,2.439450,0.705,0.152,1.931425e-69,23,smooth muscle
42711,CRISPLD2,2.674090e-160,2.557265,0.712,0.097,7.934292e-156,22,smooth muscle
21703,GPAT3,0.000000e+00,2.441945,0.715,0.132,0.000000e+00,11,Adipocyte
44526,LMOD1,1.608442e-158,2.214490,0.732,0.079,4.772408e-154,23,smooth muscle
42690,RCAN2,2.180997e-294,2.308611,0.739,0.057,6.471236e-290,22,smooth muscle
44538,SYNPO2,4.892580e-81,2.767583,0.777,0.179,1.451677e-76,23,smooth muscle
16658,NFATC1,0.000000e+00,2.366070,0.778,0.220,0.000000e+00,8,Endo
30474,PIK3R3,0.000000e+00,2.260133,0.802,0.200,0.000000e+00,16,Endo
5717,MAMDC2,0.000000e+00,2.275344,0.834,0.184,0.000000e+00,3,M2 Macrophage
5716,LGMN,0.000000e+00,2.414273,0.837,0.154,0.000000e+00,3,M2 Macrophage
44516,ITGA8,0.000000e+00,2.977793,0.839,0.033,0.000000e+00,23,smooth muscle
14804,BTNL9,0.000000e+00,2.310956,0.860,0.169,0.000000e+00,7,Endo
32328,COL25A1,0.000000e+00,2.979687,0.868,0.100,0.000000e+00,17,smooth muscle
16602,STOX2,0.000000e+00,2.344452,0.868,0.268,0.000000e+00,8,Endo
5718,MTSS1,0.000000e+00,2.243851,0.876,0.311,0.000000e+00,3,M2 Macrophage
42718,CACNA1C,8.690948e-139,2.754800,0.876,0.194,2.578691e-134,22,smooth muscle
25256,CLSTN2,0.000000e+00,2.661687,0.881,0.307,0.000000e+00,13,Adipocyte
14823,VWF,0.000000e+00,2.331605,0.899,0.182,0.000000e+00,7,Endo
42770,ZFHX3,1.517256e-71,2.283343,0.908,0.483,4.501852e-67,22,smooth muscle
37400,UPK3B,0.000000e+00,2.260602,0.912,0.128,0.000000e+00,20,Fibroblast
5715,F13A1,0.000000e+00,2.707406,0.913,0.159,0.000000e+00,3,M2 Macrophage
42747,SORBS2,7.037966e-91,2.322724,0.915,0.331,2.088235e-86,22,smooth muscle
37423,KRT19,0.000000e+00,2.576899,0.929,0.208,0.000000e+00,20,Fibroblast
37418,CRIP1,0.000000e+00,2.558085,0.932,0.186,0.000000e+00,20,Fibroblast
37431,TIMP1,0.000000e+00,2.743667,0.943,0.157,0.000000e+00,20,Fibroblast
14816,KIAA1217,0.000000e+00,2.456196,0.947,0.605,0.000000e+00,7,Endo
40682,FLRT2,7.732772e-126,2.412733,0.948,0.446,2.294391e-121,21,Fibroblast
12425,NEBL,0.000000e+00,2.472016,0.948,0.204,0.000000e+00,6,Fibroblast
42727,RGS6,7.595093e-123,3.069009,0.954,0.286,2.253540e-118,22,smooth muscle
4276,ABCA10,0.000000e+00,2.260764,0.955,0.420,0.000000e+00,2,Fibroblast
37436,TM4SF1,1.598431e-298,2.611780,0.955,0.273,4.742705e-294,20,Fibroblast
37471,TPT1,2.068741e-225,2.301055,0.957,0.413,6.138161e-221,20,Fibroblast
37446,TMSB4X,2.353493e-278,2.493527,0.960,0.316,6.983050e-274,20,Fibroblast
20058,SDK1,0.000000e+00,2.773111,0.960,0.404,0.000000e+00,10,Fibroblast
30491,ARL15,3.051945e-269,3.110763,0.963,0.696,9.055425e-265,16,Endo
12400,SULF1,0.000000e+00,2.350707,0.964,0.353,0.000000e+00,6,Fibroblast
37454,ITLN1,2.373694e-262,3.544344,0.966,0.349,7.042987e-258,20,Fibroblast
7966,KCNT2,0.000000e+00,2.237492,0.969,0.465,0.000000e+00,4,Fibroblast
37450,PRG4,4.259049e-266,2.794038,0.969,0.328,1.263702e-261,20,Fibroblast
30492,MECOM,3.054685e-269,2.255519,0.974,0.624,9.063557e-265,16,Endo
5719,FRMD4B,0.000000e+00,2.242924,0.976,0.516,0.000000e+00,3,M2 Macrophage
5714,RBPJ,0.000000e+00,2.919522,0.983,0.614,0.000000e+00,3,M2 Macrophage
37474,EEF1A1,6.735914e-220,2.488422,0.986,0.564,1.998613e-215,20,Fibroblast
4238,KAZN,0.000000e+00,2.206649,0.986,0.592,0.000000e+00,2,Fibroblast
40675,ROR1,1.584248e-134,2.341065,0.991,0.459,4.700623e-130,21,Fibroblast
20079,FBN1,0.000000e+00,2.517664,0.992,0.652,0.000000e+00,10,Fibroblast
37475,CCDC80,1.171591e-219,2.783324,0.997,0.575,3.476229e-215,20,Fibroblast
21720,ACACB,0.000000e+00,2.240868,1.000,0.840,0.000000e+00,11,Adipocyte

In [128]:
markers.groupby(col_ct)[col_rank].mean().sort_values()

cluster_name
smooth muscle    0.789231
Endo             0.796273
Adipocyte        0.865333
M2 Macrophage    0.903167
Fibroblast       0.960950
Name: pct.1, dtype: float64

In [129]:
markers[col_ct].value_counts()

cluster_name
Fibroblast       20
smooth muscle    13
Endo             11
M2 Macrophage     6
Adipocyte         3
Name: count, dtype: int64

## Convert to evidence json

In [130]:
df = markers[[col_ct, col_gene]].rename(columns={col_ct : "cell_type_label", col_gene: "feature_name"})
df["organism"] = organism
df["cell_source"] = cell_source
df["cell_state"] = cell_state
df["feature_identifier"] = df["feature_name"]
# df["feature_identifier"] = df["feature_identifier"].apply(run)
df["feature_identifier"] = None
save = df.to_dict(orient = "records")

result = [] 

for _, row in df.iterrows():
    result.append({"extracted": {"organism": row["organism"], "cell_type_label": row["cell_type_label"], "cell_source": row["cell_source"], "cell_state": row["cell_state"], "feature_name": row["feature_name"], "feature_type": "gene"},
                   "derived": {"organism": row["organism"], "cell_type_id": None, "cell_type_label": row["cell_type_label"], "cell_source": row["cell_source"], "cell_state": row["cell_state"], "feature_name": row["feature_name"], "feature_type": "gene", "feature_identifier": row["feature_identifier"], "feature_type": "ensembl"},
                   "source": {"source_type": "deg", "source_rationale": "filtered", "source_id": "deg"}})

result

[{'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NKAIN2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NKAIN2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ADGRL3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ADGRL3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FAM155A',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FAM155A',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AL357507.1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'AL357507.1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PCDH7',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PCDH7',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KCNMA1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KCNMA1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CRISPLD2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CRISPLD2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GPAT3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'GPAT3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LMOD1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LMOD1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'RCAN2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'RCAN2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SYNPO2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SYNPO2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NFATC1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NFATC1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PIK3R3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'PIK3R3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MAMDC2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MAMDC2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LGMN',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'LGMN',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ITGA8',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ITGA8',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'BTNL9',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'BTNL9',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'COL25A1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'COL25A1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'STOX2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'STOX2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MTSS1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'MTSS1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CACNA1C',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CACNA1C',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CLSTN2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Adipocyte',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CLSTN2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'VWF',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'VWF',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ZFHX3',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ZFHX3',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'UPK3B',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'UPK3B',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'F13A1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'M2 Macrophage',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'F13A1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SORBS2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'SORBS2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KRT19',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KRT19',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CRIP1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'CRIP1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TIMP1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TIMP1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KIAA1217',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Endo',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'KIAA1217',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FLRT2',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'FLRT2',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NEBL',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'NEBL',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'RGS6',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'smooth muscle',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'RGS6',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ABCA10',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'ABCA10',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TM4SF1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TM4SF1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TPT1',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TPT1',
   'feature_type': 'ensembl',
   'feature_identifier': None},
  'source': {'source_type': 'deg',
   'source_rationale': 'filtered',
   'source_id': 'deg'}},
 {'extracted': {'organism': 'homo_sapiens',
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB4X',
   'feature_type': 'gene'},
  'derived': {'organism': 'homo_sapiens',
   'cell_type_id': None,
   'cell_type_label': 'Fibroblast',
   'cell_source': 'adipose',
   'cell_state': None,
   'feature_name': 'TMSB4X',
   'feature_type': 'ensembl',

## Save evidence

In [131]:
with open("evidence_angueira.json", "w") as f:
    json.dump(result, f, indent = 4)