In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import json 
import itertools

fsize = 20
plt.rcParams.update({"font.size": fsize})
%config InlineBackend.figure_format = 'retina'

In [26]:
def load_evidence(fn):
    df = pd.read_json(fn)
    # Unwrap the 'source' column (contains a dictionary) into separate columns
    source_df = df['source'].apply(pd.Series)
    extracted_df = df['extracted'].apply(pd.Series).add_prefix('extracted_')
    # derived_df = df['derived'].apply(pd.Series).add_prefix('derived_')
    # Combine the original DataFrame with the unwrapped columns
    # df = pd.concat([df.drop(columns=['source', 'extracted', 'derived']), source_df, extracted_df, derived_df], axis=1)
    df = pd.concat([df.drop(columns=['source', 'extracted']), source_df, extracted_df], axis=1)
    del df["derived"]
    return df

In [135]:
fn_human = "../data/adipose_Massier2023/evidence_human/evidence.json"
# fn_human = "../data/adipose_Emont2022/evidence_human/evidence.json"

deg = load_evidence(fn_human)

In [136]:
deg.head()

,source_type,source_rationale,source_id,extracted_organism,extracted_cell_type_label,extracted_cell_source,extracted_cell_state,extracted_feature_name,extracted_feature_type
0,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD4+ T cells,White Adipose Tissue,none,CD4,gene
1,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD8+ T cells,White Adipose Tissue,none,CD8,gene
2,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD16+ NK (Natural Killer) Cells,White Adipose Tissue,none,CD16,gene
3,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,TIMP1,gene
4,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,ITLN1,gene

In [137]:
import re

def tokenize_with_offsets(text):
    """Tokenizes text and returns tokens with their character start positions."""
    tokens = []
    positions = []
    for match in re.finditer(r'\b\w+\b', text):  # Word-level tokenization
        tokens.append(match.group(0))
        positions.append((match.start(), match.start() + len(match.group(0))))  # Store start position in original text
    return tokens, positions

from collections import defaultdict
def index_source(source):
  source_tokens, source_positions = tokenize_with_offsets(source)
  source_index = defaultdict(list)
  for i, token in enumerate(source_tokens):
    source_index[token].append(source_positions[i])
  return source_index

def align_target(target, source_index):
  target_tokens, _ = tokenize_with_offsets(target)
  target_positions = []
  for token in target_tokens:
    if token in source_index.keys():
      target_positions.append(source_index[token].pop(0))
  return target_positions

def reconstruct_target(source, pos):
  return " ".join([source[i[0]: i[1]] for i in pos])

In [138]:
deg.head()

,source_type,source_rationale,source_id,extracted_organism,extracted_cell_type_label,extracted_cell_source,extracted_cell_state,extracted_feature_name,extracted_feature_type
0,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD4+ T cells,White Adipose Tissue,none,CD4,gene
1,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD8+ T cells,White Adipose Tissue,none,CD8,gene
2,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD16+ NK (Natural Killer) Cells,White Adipose Tissue,none,CD16,gene
3,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,TIMP1,gene
4,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,ITLN1,gene

In [139]:
tdeg = deg.query("source_type == 'text'").copy()

In [140]:
tdeg["len_extracted_cell_type_label"] = tdeg["extracted_cell_type_label"].apply(lambda x: len(x.split(" ")))
tdeg["pos_extracted_cell_type_label"] = tdeg.apply(
    lambda row: align_target(row["extracted_cell_type_label"], index_source(row["source_rationale"])), axis=1
)
tdeg["len_extracted_cell_type_label"] = tdeg["extracted_cell_type_label"].apply(lambda x: len(x.split(" ")))
tdeg["num_extracted_cell_type_label"] = tdeg.apply(
    lambda row: len(align_target(row["extracted_cell_type_label"], index_source(row["source_rationale"]))), axis=1
)
tdeg["found_extracted_cell_type"] = tdeg["len_extracted_cell_type_label"] == tdeg["num_extracted_cell_type_label"]

In [141]:
tdeg["len_extracted_feature_name"] = tdeg["extracted_feature_name"].apply(lambda x: len(x.split(" ")))
tdeg["pos_extracted_feature_name"] = tdeg.apply(
    lambda row: align_target(row["extracted_feature_name"], index_source(row["source_rationale"])), axis=1
)
tdeg["num_extracted_feature_name"] = tdeg.apply(
    lambda row: len(align_target(row["extracted_feature_name"], index_source(row["source_rationale"]))), axis=1
)
tdeg["found_extracted_feature_name"] = tdeg["len_extracted_feature_name"] == tdeg["num_extracted_feature_name"]

In [147]:
print("Genes found: , ", tdeg["found_extracted_feature_name"].sum())
print("Cell types found: , ", tdeg["found_extracted_cell_type"].sum())

Genes found: ,  29
Cell types found: ,  2

In [143]:
tdeg.shape

(29, 17)

In [144]:
tdeg

,source_type,source_rationale,source_id,extracted_organism,extracted_cell_type_label,extracted_cell_source,extracted_cell_state,extracted_feature_name,extracted_feature_type,len_extracted_cell_type_label,pos_extracted_cell_type_label,num_extracted_cell_type_label,found_extracted_cell_type,len_extracted_feature_name,pos_extracted_feature_name,num_extracted_feature_name,found_extracted_feature_name
0,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD4+ T cells,White Adipose Tissue,none,CD4,gene,3,"[(161, 164), (166, 167), (168, 173)]",3,True,1,"[(161, 164)]",1,True
1,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD8+ T cells,White Adipose Tissue,none,CD8,gene,3,"[(179, 182), (166, 167), (168, 173)]",3,True,1,"[(179, 182)]",1,True
2,text,These included subtypes of (i) Th1-polarized (...,text,homo_sapiens,CD16+ NK (Natural Killer) Cells,White Adipose Tissue,none,CD16,gene,5,"[(297, 301), (329, 331)]",2,False,1,"[(297, 301)]",1,True
3,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,TIMP1,gene,3,[],0,False,1,"[(263, 268)]",1,True
4,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,myCO8 (M2-like macrophage),White Adipose Tissue,none,ITLN1,gene,3,[],0,False,1,"[(273, 278)]",1,True
5,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,vC08 (blood vascular cells),White Adipose Tissue,none,TIMP1,gene,4,"[(41, 45), (170, 175)]",2,False,1,"[(263, 268)]",1,True
6,text,Top marker genes for these revealed that vC08 ...,text,homo_sapiens,vC08 (blood vascular cells),White Adipose Tissue,none,ITLN1,gene,4,"[(41, 45), (170, 175)]",2,False,1,"[(273, 278)]",1,True
7,text,vC09 was enriched for genes previously describ...,text,homo_sapiens,vC09 (blood vascular cells),White Adipose Tissue,none,TYROBP,gene,4,"[(0, 4), (82, 87)]",2,False,1,"[(96, 102)]",1,True
8,text,vC09 was enriched for genes previously describ...,text,homo_sapiens,vC09 (blood vascular cells),White Adipose Tissue,none,FCER1G,gene,4,"[(0, 4), (82, 87)]",2,False,1,"[(104, 110)]",1,True
9,text,One vascular subtype (vC05) expressed multiple...,text,homo_sapiens,vC05 (blood vascular cells),White Adipose Tissue,none,CXCL14,gene,4,"[(22, 26), (4, 12)]",2,False,1,"[(95, 101)]",1,True
10,text,One vascular subtype (vC05) expressed multiple...,text,homo_sapiens,vC05 (blood vascular cells),White Adipose Tissue,none,APOD,gene,4,"[(22, 26), (4, 12)]",2,False,1,"[(103, 107)]",1,True
11,text,One vascular subtype (vC05) expressed multiple...,text,homo_sapiens,vC05 (blood vascular cells),White Adipose Tissue,none,CFD,gene,4,"[(22, 26), (4, 12)]",2,False,1,"[(113, 116)]",1,True
12,text,One vascular subtype (vC05) expressed multiple...,text,homo_sapiens,vC05 (blood vascular cells),White Adipose Tissue,none,PDGFRA,gene,4,"[(22, 26), (4, 12)]",2,False,1,"[(170, 176)]",1,True
13,text,The former included mesothelial-like cells (sf...,text,homo_sapiens,Stromal cells (sfC13),White Adipose Tissue,none,CD74,gene,3,"[(37, 42), (73, 78)]",2,False,1,"[(52, 56)]",1,True
14,text,Our results show that the CD55/PI16 gene clust...,text,homo_sapiens,Adipose precluster (sfC02),White Adipose Tissue,none,CD55,gene,3,"[(50, 55)]",1,False,1,"[(26, 30)]",1,True
15,text,Our results show that the CD55/PI16 gene clust...,text,homo_sapiens,Adipose precluster (sfC02),White Adipose Tissue,none,PI16,gene,3,"[(50, 55)]",1,False,1,"[(31, 35)]",1,True
16,text,"Route 1 ended in sfC0, a cell population enric...",text,homo_sapiens,Preadipocytes (sfC0),White Adipose Tissue,none,APOD,gene,2,"[(17, 21)]",1,False,1,"[(123, 127)]",1,True
17,text,"Route 1 ended in sfC0, a cell population enric...",text,homo_sapiens,Preadipocytes (sfC0),White Adipose Tissue,none,CFD,gene,2,"[(17, 21)]",1,False,1,"[(132, 135)]",1,True
18,text,[...] suggesting that under standard in vitro ...,text,homo_sapiens,Adipocyte precluster cells,White Adipose Tissue,standard in vitro,CD55,gene,3,"[(84, 89)]",1,False,1,"[(58, 62)]",1,True
19,text,"Thus, CD55/PI16-expressing adipose precursors ...",text,homo_sapiens,ofC07 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,CD55,gene,6,"[(62, 67), (69, 72)]",2,False,1,"[(6, 10)]",1,True
20,text,"Thus, CD55/PI16-expressing adipose precursors ...",text,homo_sapiens,ofC07 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,PI16,gene,6,"[(62, 67), (69, 72)]",2,False,1,"[(11, 15)]",1,True
21,text,"Thus, CD55/PI16-expressing adipose precursors ...",text,homo_sapiens,ofC02 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,APOD,gene,6,"[(140, 145), (69, 72)]",2,False,1,"[(73, 77)]",1,True
22,text,"Thus, CD55/PI16-expressing adipose precursors ...",text,homo_sapiens,ofC02 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,CFD,gene,6,"[(140, 145), (69, 72)]",2,False,1,"[(78, 81)]",1,True
23,text,CD74 was highly enriched in sfC13 and ofC10,text,homo_sapiens,ofC10 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,CD74,gene,6,"[(39, 44), (35, 38)]",2,False,1,"[(1, 5)]",1,True
24,text,The mesothelial-like cell signature in subcuta...,text,homo_sapiens,ofC03 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,DPP4,gene,6,"[(108, 113), (94, 101), (122, 125)]",3,False,1,"[(146, 150)]",1,True
25,text,The mesothelial-like cell signature in subcuta...,text,homo_sapiens,ofC06 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,DPP4,gene,6,"[(115, 120), (94, 101), (122, 125)]",3,False,1,"[(146, 150)]",1,True
26,text,The mesothelial-like cell signature in subcuta...,text,homo_sapiens,ofC11 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,DPP4,gene,6,"[(126, 131), (94, 101), (122, 125)]",3,False,1,"[(146, 150)]",1,True
27,text,The mesothelial-like cell signature in subcuta...,text,homo_sapiens,ofC12 (omental Fibroblast and Adipogenic Proge...,White Adipose Tissue,none,DPP4,gene,6,"[(94, 101), (122, 125)]",2,False,1,"[(146, 150)]",1,True
28,text,Flow cytometric analysis of subtype-specific s...,text,homo_sapiens,Mesothlial-Like Cells,White Adipose Tissue,none,EZR,gene,2,[],0,False,1,"[(258, 261)]",1,True