In [1]:
import pandas as pd
import numpy as np
import json

## Define the metadata

In [2]:
organism = "homo_sapiens"
cell_source = "lung"
cell_state = None

reference = "GRCh38"
paper_doi = "https://doi.org/10.1126/sciadv.aba1983"
table_link = "https://www.science.org/doi/suppl/10.1126/sciadv.aba1983/suppl_file/aba1983_data_s2.txt"

# don't include in header
table_names = ["downloadSupplement.txt", "downloadSupplement2.txt", "downloadSupplement3.txt", "downloadSupplement4.txt", "downloadSupplement5.txt"]

## Read in file

In [12]:
#excel = pd.read_excel(table_name, sheet_name = ["Degs human_limb&bone Fig. 1d", "Degs human long bone Fig. S3b", "Degs human calvaria Fig. 6b"], skiprows = 0)
tables = []
for tn in table_names:
    tables.append(pd.read_csv(tn, sep = "\t"))
df = pd.concat(tables)
df.rename(columns = {"wilcox.p": "p_val_adj"}, inplace=True)

df

,cellType,gene,log1p_FC,pct.inGroup,pct.outGroup,p_val_adj,wilcox.fdr,wilcox.bonferroni
1,Basal,MIR205HG,1.757514,0.969231,0.489669,8.086494e-39,2.838360e-36,2.838360e-36
2,Basal,KRT5,0.750194,0.861538,0.264463,3.598166e-36,6.314782e-34,1.262956e-33
3,Basal,EYA2,1.436151,0.984615,0.669421,1.463281e-33,1.712039e-31,5.136117e-31
4,Basal,CYP24A1,0.678724,0.892308,0.320248,4.873706e-32,4.276677e-30,1.710671e-29
5,Basal,KRT17,1.943518,0.953846,0.526860,2.228007e-31,1.564061e-29,7.820306e-29
...,...,...,...,...,...,...,...,...
2924,ILC B,PARP8,-0.325149,0.923077,0.944015,1.614698e-03,1.637124e-03,4.714917e-01
2925,ILC B,PHF20,0.315690,0.969231,0.978764,1.810093e-03,1.828883e-03,5.285472e-01
2926,ILC B,TOB1,0.321810,0.815385,0.870656,8.323321e-03,8.323321e-03,1.000000e+00
2927,ILC B,PRKG1,0.351816,0.553846,0.669884,4.134930e-03,4.163446e-03,1.000000e+00
2928,ILC B,ENSG00000240040,-0.683390,0.523077,0.727799,5.248595e-03,5.266631e-03,1.000000e+00

In [13]:
df.head()

,cellType,gene,log1p_FC,pct.inGroup,pct.outGroup,p_val_adj,wilcox.fdr,wilcox.bonferroni
1,Basal,MIR205HG,1.757514,0.969231,0.489669,8.086494e-39,2.838360e-36,2.838360e-36
2,Basal,KRT5,0.750194,0.861538,0.264463,3.598166e-36,6.314782e-34,1.262956e-33
3,Basal,EYA2,1.436151,0.984615,0.669421,1.463281e-33,1.712039e-31,5.136117e-31
4,Basal,CYP24A1,0.678724,0.892308,0.320248,4.873706e-32,4.276677e-30,1.710671e-29
5,Basal,KRT17,1.943518,0.953846,0.526860,2.228007e-31,1.564061e-29,7.820306e-29

## Perform the filtering

In [14]:
col_pval = "p_val_adj"
col_lfc = "log1p_FC"
col_gene = "gene"
col_ct = "cellType" 
col_rank = "pct.inGroup" # set to None if pct. 1DNE

In [15]:
min_mean = 100
max_pval = 1e-10
min_lfc = 2.2
max_gene_shares = 2
max_per_celltype = 20

# filter by pval and lfc
dfc = df.query(f"{col_pval} <= {max_pval} & {col_lfc} >= {min_lfc}")

# mask out genes that are shared between max_gene_shares cell types
non_repeat_genes = dfc[col_gene].value_counts()[dfc[col_gene].value_counts() < max_gene_shares].index.values

m = dfc[dfc[col_gene].isin(non_repeat_genes)]

if col_rank:
    m = m.sort_values(col_rank, ascending = True)

# max number to sample is equal to the min number of genes across all celltype
n_sample = min(m[col_ct].value_counts().max(), max_per_celltype)

# sample n_sample genes
markers = m.groupby(col_ct).tail(n_sample)
markers_dict = markers.groupby(col_ct)[col_gene].apply(lambda x: list(x)).to_dict()

## Check how many genes per cell type

In [16]:
markers

,cellType,gene,log1p_FC,pct.inGroup,pct.outGroup,p_val_adj,wilcox.fdr,wilcox.bonferroni
1022,AT1,NTM,2.208726,0.833333,0.687631,3.074875e-18,1.079376e-17,2.093990e-15
5881,PNEC,SEC11C,2.493893,0.875000,0.746667,9.400886e-11,1.405860e-09,6.185783e-08
5838,PNEC,GRP,3.643086,0.875000,0.009524,3.142829e-86,2.067981e-83,2.067981e-83
1165,B Plasma,IGHA1,2.316354,0.911765,0.559223,8.953227e-32,1.934440e-30,6.383651e-29
849,AT1,NCKAP5,2.210212,0.944444,0.710692,4.801476e-35,1.557050e-33,3.269805e-32
358,AT2,SFTPC,3.597459,0.945946,0.602105,6.564154e-37,4.473002e-35,3.131101e-34
3479,Mast,IL1RL1,2.302870,0.954545,0.384117,2.593922e-43,2.564741e-41,2.051793e-40
1136,B Plasma,JCHAIN,3.162226,0.955882,0.413592,5.750390e-42,1.025007e-39,4.100028e-39
5853,PNEC,NRG1,2.798002,0.958333,0.809524,2.566611e-14,1.055519e-12,1.688830e-11
2833,DC Langerhans,S100B,2.757214,0.960000,0.630332,7.566173e-29,9.730098e-27,4.865049e-26
3386,Mesothelial,ITLN1,2.222389,0.962264,0.163306,1.134665e-52,1.660393e-50,9.962356e-50
829,AT1,AGER,2.561969,0.972222,0.423480,6.358255e-45,4.329972e-42,4.329972e-42
3413,Mesothelial,TIMP1,2.608638,0.981132,0.810484,1.197953e-30,3.143571e-29,1.051803e-27
3066,Goblet,BPIFB1,2.644283,0.984615,0.450413,8.509092e-42,2.680364e-39,2.680364e-39
3073,Goblet,SCGB1A1,4.172826,0.984615,0.754132,8.644757e-35,3.403873e-33,2.723098e-32
831,AT1,CAV1,2.497446,0.986111,0.708595,3.675006e-41,8.342264e-39,2.502679e-38
1795,Ciliated,DNAH9,2.378801,0.986842,0.581395,2.783485e-44,1.358652e-43,3.885746e-41
1788,Ciliated,HYDIN,2.502899,0.986842,0.600423,1.884255e-44,9.428029e-44,2.630420e-41
1752,Ciliated,LRRIQ1,2.325434,0.986842,0.520085,1.874145e-45,1.076669e-44,2.616306e-42
1772,Ciliated,CAPS,2.301882,0.986842,0.564482,6.501696e-45,3.451091e-44,9.076368e-42
1747,Ciliated,CFAP299,2.839444,0.986842,0.526427,1.451943e-45,8.516438e-45,2.026912e-42
1853,Ciliated,AGBL4,2.544159,0.986842,0.765328,1.292841e-42,5.246527e-42,1.804805e-39
1823,Ciliated,RP1,2.418771,0.986842,0.657505,1.552193e-43,6.900831e-43,2.166861e-40
1816,Ciliated,TMEM232,2.240583,0.986842,0.575053,9.044718e-44,4.112842e-43,1.262643e-40
1803,Ciliated,DNAH12,2.887247,0.986842,0.602537,4.277440e-44,2.031057e-43,5.971307e-41
1697,Ciliated,RSPH1,2.322858,0.986842,0.465116,2.136358e-47,1.586359e-46,2.982356e-44
379,B,CD74,2.286179,1.000000,0.954635,1.901340e-44,5.428325e-43,1.085665e-41
3477,Mast,TPSB2,4.677957,1.000000,0.337115,2.161259e-51,2.849260e-49,1.709556e-48
32,NK,CCL4,2.302470,1.000000,0.715415,2.659896e-39,2.984070e-38,9.549025e-37
17,NK,NKG7,2.411388,1.000000,0.650198,1.131391e-42,2.389232e-41,4.061694e-40
4277,pDC,FCHSD2,2.755100,1.000000,0.944708,8.454713e-32,5.061555e-30,7.592332e-29
4272,pDC,IRF4,2.381533,1.000000,0.750395,3.244546e-32,2.913602e-30,2.913602e-29
4268,pDC,GZMB,2.802810,1.000000,0.519747,6.847935e-35,1.024908e-32,6.149446e-32
1743,Ciliated,CDHR3,2.207381,1.000000,0.602537,9.678797e-46,5.774188e-45,1.351160e-42
40,NK,GNLY,2.346004,1.000000,0.662055,8.550578e-38,7.674144e-37,3.069658e-35
471,Macrophage Alveolar,APOC1,2.582470,1.000000,0.919008,4.930203e-45,1.299930e-43,3.899790e-42
1238,cMonocyte,S100A9,2.578953,1.000000,0.810231,2.583504e-45,1.842899e-43,1.105740e-42
1237,cMonocyte,S100A8,2.606286,1.000000,0.765677,1.614429e-45,1.381951e-43,6.909755e-43
476,Macrophage Alveolar,C1QA,2.258833,1.000000,0.869421,6.138073e-45,1.350523e-43,4.855216e-42
461,Macrophage Alveolar,FABP4,2.209686,1.000000,0.780165,6.697607e-47,2.648904e-45,5.297807e-44
370,AT2,SFTPB,2.612695,1.000000,0.827368,2.913820e-31,7.315222e-30,1.389892e-28
4930,Ionocyte,PDE1C,2.619220,1.000000,0.490672,4.881790e-11,3.738637e-09,4.486365e-08
3421,Mesothelial,MT2A,2.610366,1.000000,0.919355,6.879550e-29,1.473230e-27,6.040245e-26
1137,B Plasma,ENSG00000240040,4.364972,1.000000,0.666019,1.681227e-41,2.397429e-39,1.198715e-38
3081,Goblet,SLPI,2.324959,1.000000,0.869835,1.428444e-30,2.812250e-29,4.499599e-28
3071,Goblet,SCGB3A1,4.552035,1.000000,0.778926,5.727305e-36,3.006835e-34,1.804101e-33
3476,Mast,TPSAB1,4.359838,1.000000,0.329011,6.774937e-52,1.071795e-49,5.358975e-49
830,AT1,EMP2,2.689831,1.000000,0.895178,2.764399e-42,9.412780e-40,1.882556e-39

## Find Ensembl ID

In [17]:
import sys
import time

from urllib.parse import urlparse, urlencode
from urllib.request import urlopen, Request
from urllib.error import HTTPError

In [18]:
class EnsemblRestClient(object):
    def __init__(self, server='http://rest.ensembl.org', reqs_per_sec=5):
        self.server = server
        self.reqs_per_sec = reqs_per_sec
        self.req_count = 0
        self.last_req = 0

    def perform_rest_action(self, endpoint, hdrs=None, params=None):
        if hdrs is None:
            hdrs = {}

        if 'Content-Type' not in hdrs:
            hdrs['Content-Type'] = 'application/json'

        if params:
            endpoint += '?' + urlencode(params)

        data = None

        # check if we need to rate limit ourselves
        if self.req_count >= self.reqs_per_sec:
            delta = time.time() - self.last_req
            if delta < 1:
                time.sleep(1 - delta)
            self.last_req = time.time()
            self.req_count = 0
        
        try:
            request = Request(self.server + endpoint, headers=hdrs)
            response = urlopen(request)
            content = response.read()
            if content:
                data = json.loads(content)
            self.req_count += 1

        except HTTPError as e:
            # check if we are being rate limited by the server
            if e.code == 429:
                if 'Retry-After' in e.headers:
                    retry = e.headers['Retry-After']
                    time.sleep(float(retry))
                    self.perform_rest_action(endpoint, hdrs, params)
            else:
                sys.stderr.write('Request failed for {0}: Status code: {1.code} Reason: {1.reason}\n'.format(endpoint, e))
           
        return data

    def get_id(self, species, symbol):
        genes = self.perform_rest_action(
            endpoint='/xrefs/symbol/{0}/{1}'.format(species, symbol), 
            params={'object_type': 'gene'}
        )
        if genes:
            stable_id = genes[0]['id']
            return stable_id
        else:
            return "gene not found"

In [19]:
def run(symbol):
    client = EnsemblRestClient()
    gene_id = client.get_id('human', symbol)
    return gene_id

## Convert to evidence json

In [20]:
df = markers[[col_ct, col_gene]].rename(columns={col_ct : "cell_type_label", col_gene: "gene"})
df["organism"] = organism
df["cell_source"] = cell_source
df["cell_state"] = cell_state
df["gene_id"] = df["gene"]
df["gene_id"] = df["gene_id"].apply(run)
save = df.to_dict(orient = "records")

In [21]:
save

[{'cell_type_label': 'AT1',
  'gene': 'NTM',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000182667'},
 {'cell_type_label': 'PNEC',
  'gene': 'SEC11C',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000166562'},
 {'cell_type_label': 'PNEC',
  'gene': 'GRP',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000165623'},
 {'cell_type_label': 'B Plasma',
  'gene': 'IGHA1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000211895'},
 {'cell_type_label': 'AT1',
  'gene': 'NCKAP5',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000176771'},
 {'cell_type_label': 'AT2',
  'gene': 'SFTPC',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000168484'},
 {'cell_type_label': 'Mast',
  'gene': 'IL1RL1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000115602'},
 {'cell_type_label': 'B Plasma',
  'gene': 'JCHAIN',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000132465'},
 {'cell_type_label': 'PNEC',
  'gene': 'NRG1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000157168'},
 {'cell_type_label': 'DC Langerhans',
  'gene': 'S100B',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000160307'},
 {'cell_type_label': 'Mesothelial',
  'gene': 'ITLN1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000179914'},
 {'cell_type_label': 'AT1',
  'gene': 'AGER',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000204305'},
 {'cell_type_label': 'Mesothelial',
  'gene': 'TIMP1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000102265'},
 {'cell_type_label': 'Goblet',
  'gene': 'BPIFB1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000125999'},
 {'cell_type_label': 'Goblet',
  'gene': 'SCGB1A1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000149021'},
 {'cell_type_label': 'AT1',
  'gene': 'CAV1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000105974'},
 {'cell_type_label': 'Ciliated',
  'gene': 'DNAH9',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000007174'},
 {'cell_type_label': 'Ciliated',
  'gene': 'HYDIN',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000157423'},
 {'cell_type_label': 'Ciliated',
  'gene': 'LRRIQ1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000133640'},
 {'cell_type_label': 'Ciliated',
  'gene': 'CAPS',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000163618'},
 {'cell_type_label': 'Ciliated',
  'gene': 'CFAP299',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000197826'},
 {'cell_type_label': 'Ciliated',
  'gene': 'AGBL4',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000186094'},
 {'cell_type_label': 'Ciliated',
  'gene': 'RP1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000166974'},
 {'cell_type_label': 'Ciliated',
  'gene': 'TMEM232',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000186952'},
 {'cell_type_label': 'Ciliated',
  'gene': 'DNAH12',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000174844'},
 {'cell_type_label': 'Ciliated',
  'gene': 'RSPH1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000160188'},
 {'cell_type_label': 'B',
  'gene': 'CD74',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000019582'},
 {'cell_type_label': 'Mast',
  'gene': 'TPSB2',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000197253'},
 {'cell_type_label': 'NK',
  'gene': 'CCL4',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000275302'},
 {'cell_type_label': 'NK',
  'gene': 'NKG7',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000105374'},
 {'cell_type_label': 'pDC',
  'gene': 'FCHSD2',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000137478'},
 {'cell_type_label': 'pDC',
  'gene': 'IRF4',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000137265'},
 {'cell_type_label': 'pDC',
  'gene': 'GZMB',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000100453'},
 {'cell_type_label': 'Ciliated',
  'gene': 'CDHR3',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000128536'},
 {'cell_type_label': 'NK',
  'gene': 'GNLY',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000115523'},
 {'cell_type_label': 'Macrophage Alveolar',
  'gene': 'APOC1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000130208'},
 {'cell_type_label': 'cMonocyte',
  'gene': 'S100A9',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000163220'},
 {'cell_type_label': 'cMonocyte',
  'gene': 'S100A8',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000143546'},
 {'cell_type_label': 'Macrophage Alveolar',
  'gene': 'C1QA',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000173372'},
 {'cell_type_label': 'Macrophage Alveolar',
  'gene': 'FABP4',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000170323'},
 {'cell_type_label': 'AT2',
  'gene': 'SFTPB',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000168878'},
 {'cell_type_label': 'Ionocyte',
  'gene': 'PDE1C',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000154678'},
 {'cell_type_label': 'Mesothelial',
  'gene': 'MT2A',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000125148'},
 {'cell_type_label': 'B Plasma',
  'gene': 'ENSG00000240040',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000240040'},
 {'cell_type_label': 'Goblet',
  'gene': 'SLPI',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000124107'},
 {'cell_type_label': 'Goblet',
  'gene': 'SCGB3A1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000161055'},
 {'cell_type_label': 'Mast',
  'gene': 'TPSAB1',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000172236'},
 {'cell_type_label': 'AT1',
  'gene': 'EMP2',
  'organism': 'homo_sapiens',
  'cell_source': 'lung',
  'cell_state': None,
  'gene_id': 'ENSG00000213853'}]

## Save evidence

In [22]:
with open("evidence.json", "w") as f:
    json.dump(save, f, indent = 4)