In [1]:
import pandas as pd
import numpy as np
import json

## Define the metadata

In [2]:
organism = "homo_sapiens"
cell_source = "bladder"
cell_state = None

reference = "GRCh38"
paper_doi = "https://doi.org/10.1681/ASN.2019040335",
table_link = "https://cdn-links.lww.com/permalink/jsn/c/jsn_30_11_2022_12_07_yu_2019040335_sdc5.xlsx"

# don't include in header
table_name = "jsn_30_11_2022_12_07_yu_2019040335_sdc5.xlsx"
table_name = "clean_degs.xlsx"

## Read in file

In [5]:
excel = pd.read_excel(table_name, skiprows = 1)

df = excel

In [6]:
df.head()

   p_val  avg_logFC  pct.1  pct.2  p_val_adj        cluster    gene
0    0.0   0.801753  0.994  0.625        0.0  basal cells 1  Igfbp2
1    0.0   0.765484  0.846  0.429        0.0  basal cells 1  Gsdmc2
2    0.0   0.657349  0.995  0.732        0.0  basal cells 1   Krt15
3    0.0   0.625553  0.928  0.532        0.0  basal cells 1  Acaa1b
4    0.0   0.603922  0.949  0.549        0.0  basal cells 1    Krt5

## Perform the filtering

In [7]:
col_pval = "p_val_adj"
col_lfc = "avg_logFC"
col_gene = "gene"
col_ct = "cluster" # says cluster in table, but before this had "celltype"
col_rank = "pct.1" # set to None if pct. 1DNE

In [8]:
min_mean = 100
max_pval = 1e-10
min_lfc = 2.2
max_gene_shares = 2
max_per_celltype = 20

# filter by pval and lfc
dfc = df.query(f"{col_pval} <= {max_pval} & {col_lfc} >= {min_lfc}")

# mask out genes that are shared between max_gene_shares cell types
non_repeat_genes = dfc[col_gene].value_counts()[dfc[col_gene].value_counts() < max_gene_shares].index.values

m = dfc[dfc[col_gene].isin(non_repeat_genes)]

if col_rank:
    m = m.sort_values(col_rank, ascending = True)

# max number to sample is equal to the min number of genes across all celltype
n_sample = min(m[col_ct].value_counts().max(), max_per_celltype)

# sample n_sample genes
markers = m.groupby(col_ct).tail(n_sample)
markers_dict = markers.groupby(col_ct)[col_gene].apply(lambda x: list(x)).to_dict()

## Check how many genes per cell type

In [9]:
markers

,p_val,avg_logFC,pct.1,pct.2,p_val_adj,cluster,gene
5644,0.000000e+00,2.574907,0.377,0.001,0.000000e+00,T cells,Nkg7
5642,0.000000e+00,4.359741,0.377,0.006,0.000000e+00,T cells,Ccl5
5647,0.000000e+00,2.298859,0.554,0.000,0.000000e+00,T cells,Cd3g
5646,0.000000e+00,2.347063,0.631,0.001,0.000000e+00,T cells,Trbc2
5720,3.590000e-84,2.353474,0.654,0.130,5.620000e-80,T cells,AW112010
...,...,...,...,...,...,...,...
2736,0.000000e+00,2.211725,1.000,0.361,0.000000e+00,myofibroblast,Col1a2
2735,0.000000e+00,2.300105,1.000,0.399,0.000000e+00,myofibroblast,Sparc
2734,0.000000e+00,2.396431,1.000,0.314,0.000000e+00,myofibroblast,Col1a1
2731,0.000000e+00,3.012099,1.000,0.080,0.000000e+00,myofibroblast,Car3
1347,0.000000e+00,2.393104,1.000,0.844,0.000000e+00,fibroblast 2,Gsn

In [10]:
markers.groupby(col_ct)[col_rank].mean().sort_values()

cluster
T cells                0.585857
smooth muscle cells    0.747800
dendritic cells        0.853833
fibroblast 3           0.871667
monocytes              0.889200
neurone                0.895714
endothelial cells      0.920571
fibroblast 2           0.988000
myofibroblast          0.992000
Name: pct.1, dtype: float64

In [11]:
markers[col_ct].value_counts()

cluster
monocytes              20
endothelial cells      14
smooth muscle cells    10
T cells                 7
neurone                 7
dendritic cells         6
myofibroblast           6
fibroblast 3            3
fibroblast 2            2
Name: count, dtype: int64

## Find Ensembl ID

In [12]:
import sys
import time

from urllib.parse import urlparse, urlencode
from urllib.request import urlopen, Request
from urllib.error import HTTPError

In [13]:
class EnsemblRestClient(object):
    def __init__(self, server='http://rest.ensembl.org', reqs_per_sec=5):
        self.server = server
        self.reqs_per_sec = reqs_per_sec
        self.req_count = 0
        self.last_req = 0

    def perform_rest_action(self, endpoint, hdrs=None, params=None):
        if hdrs is None:
            hdrs = {}

        if 'Content-Type' not in hdrs:
            hdrs['Content-Type'] = 'application/json'

        if params:
            endpoint += '?' + urlencode(params)

        data = None

        # check if we need to rate limit ourselves
        if self.req_count >= self.reqs_per_sec:
            delta = time.time() - self.last_req
            if delta < 1:
                time.sleep(1 - delta)
            self.last_req = time.time()
            self.req_count = 0
        
        try:
            request = Request(self.server + endpoint, headers=hdrs)
            response = urlopen(request)
            content = response.read()
            if content:
                data = json.loads(content)
            self.req_count += 1

        except HTTPError as e:
            # check if we are being rate limited by the server
            if e.code == 429:
                if 'Retry-After' in e.headers:
                    retry = e.headers['Retry-After']
                    time.sleep(float(retry))
                    self.perform_rest_action(endpoint, hdrs, params)
            else:
                sys.stderr.write('Request failed for {0}: Status code: {1.code} Reason: {1.reason}\n'.format(endpoint, e))
           
        return data

    def get_id(self, species, symbol):
        genes = self.perform_rest_action(
            endpoint='/xrefs/symbol/{0}/{1}'.format(species, symbol), 
            params={'object_type': 'gene'}
        )
        if genes:
            stable_id = genes[0]['id']
            return stable_id
        else:
            return "gene not found"

In [14]:
def run(symbol):
    client = EnsemblRestClient()
    gene_id = client.get_id('human', symbol)
    return gene_id

## Convert to evidence json

In [15]:
df = markers[[col_ct, col_gene]].rename(columns={col_ct : "cell_type_label", col_gene: "gene"})
df["organism"] = organism
df["cell_source"] = cell_source
df["cell_state"] = cell_state
df["gene_id"] = df["gene"]
df["gene_id"] = df["gene_id"].apply(run)
save = df.to_dict(orient = "records")

In [16]:
save

[{'cell_type_label': 'T cells',
  'gene': 'Nkg7',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000105374'},
 {'cell_type_label': 'T cells',
  'gene': 'Ccl5',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000271503'},
 {'cell_type_label': 'T cells',
  'gene': 'Cd3g',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000289746'},
 {'cell_type_label': 'T cells',
  'gene': 'Trbc2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000211772'},
 {'cell_type_label': 'T cells',
  'gene': 'AW112010',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'Cd209a',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'T cells',
  'gene': 'Ltb',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000227507'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Actg2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000163017'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Des',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000175084'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ccl8',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000108700'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Cnn1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000130176'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Myh11',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000133392'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'Tnip3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000050730'},
 {'cell_type_label': 'monocytes',
  'gene': 'Folr2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000165457'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Apold1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000178878'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Igfbp5',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000115461'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Tagln',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000149591'},
 {'cell_type_label': 'fibroblast 3',
  'gene': 'Gpx3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000211445'},
 {'cell_type_label': 'monocytes',
  'gene': 'F13a1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000124491'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Myl9',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000101335'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Mylk',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000065534'},
 {'cell_type_label': 'monocytes',
  'gene': 'Klf2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000127528'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Tpm2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000198467'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Csrp1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000159176'},
 {'cell_type_label': 'smooth muscle cells',
  'gene': 'Acta2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000107796'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ccl9',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ccl6',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'neurone',
  'gene': 'Msln',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000102854'},
 {'cell_type_label': 'neurone',
  'gene': 'Gpm6a',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000150625'},
 {'cell_type_label': 'T cells',
  'gene': 'Rac2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000128340'},
 {'cell_type_label': 'monocytes',
  'gene': 'Wfdc17',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Gpihbp1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000277494'},
 {'cell_type_label': 'neurone',
  'gene': 'Slpi',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000124107'},
 {'cell_type_label': 'monocytes',
  'gene': 'Cd68',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000129226'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ctss',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000163131'},
 {'cell_type_label': 'fibroblast 3',
  'gene': 'Gas1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000180447'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'Alox5ap',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000132965'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'H2-DMb1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ninj1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000131669'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Reln',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000189056'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Cp',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000047457'},
 {'cell_type_label': 'neurone',
  'gene': 'Aebp1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000106624'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Ecscr',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000249751'},
 {'cell_type_label': 'monocytes',
  'gene': 'Fcgr3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000203747'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'H2-DMa',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'neurone',
  'gene': 'C3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000125730'},
 {'cell_type_label': 'monocytes',
  'gene': 'Ctsc',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000109861'},
 {'cell_type_label': 'monocytes',
  'gene': 'Csf1r',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000182578'},
 {'cell_type_label': 'monocytes',
  'gene': 'Pf4',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000163737'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Cavin2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000168497'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Fxyd6',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000137726'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Lyve1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000133800'},
 {'cell_type_label': 'neurone',
  'gene': 'Igfbp6',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000167779'},
 {'cell_type_label': 'fibroblast 3',
  'gene': 'Lum',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000139329'},
 {'cell_type_label': 'neurone',
  'gene': 'Crip1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000119865'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Mmrn1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000138722'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Ccl21a',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'gene not found'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Rbp4',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000138207'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Cxcl14',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000145824'},
 {'cell_type_label': 'fibroblast 2',
  'gene': 'Pi16',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000164530'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Fgl2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000127951'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Gng11',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000127920'},
 {'cell_type_label': 'monocytes',
  'gene': 'Fcer1g',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000158869'},
 {'cell_type_label': 'monocytes',
  'gene': 'C1qc',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000159189'},
 {'cell_type_label': 'dendritic cells',
  'gene': 'Cst3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000101439'},
 {'cell_type_label': 'monocytes',
  'gene': 'Selenop',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000250722'},
 {'cell_type_label': 'monocytes',
  'gene': 'C1qb',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000173369'},
 {'cell_type_label': 'monocytes',
  'gene': 'C1qa',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000173372'},
 {'cell_type_label': 'endothelial cells',
  'gene': 'Cldn5',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000184113'},
 {'cell_type_label': 'monocytes',
  'gene': 'Apoe',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000130203'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Col1a2',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000164692'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Sparc',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000113140'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Col1a1',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000108821'},
 {'cell_type_label': 'myofibroblast',
  'gene': 'Car3',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000164879'},
 {'cell_type_label': 'fibroblast 2',
  'gene': 'Gsn',
  'organism': 'homo_sapiens',
  'cell_source': 'bladder',
  'cell_state': None,
  'gene_id': 'ENSG00000148180'}]

## Save evidence

In [17]:
with open("evidence.json", "w") as f:
    json.dump(save, f, indent = 4)