In [1]:
import pandas as pd
import numpy as np
import json

## Define the metadata

In [2]:
organism = "homo_sapiens"
cell_source = "bone"
cell_state = None

reference = "GRCh38"
paper_doi = "https://doi.org/10.1038/s41422-021-00467-z"
table_link = "https://static-content.springer.com/esm/art%3A10.1038%2Fs41422-021-00467-z/MediaObjects/41422_2021_467_MOESM7_ESM.xlsx"

# don't include in header
table_name = "41422_2021_467_MOESM7_ESM.xlsx"
table_name = "clean_degs.xlsx"

## Read in file

In [3]:
excel = pd.read_excel(table_name, sheet_name = ["Degs human_limb&bone Fig. 1d", "Degs human long bone Fig. S3b", "Degs human calvaria Fig. 6b"], skiprows = 0)

df = pd.concat(excel.values(), ignore_index = True)

In [4]:
df.head()

  cluster    gene  logfoldchanges  pvals_adj
0    LBM1   H2AFZ        1.734192        0.0
1    LBM1  RANBP1        1.468134        0.0
2    LBM1     NaN        1.090531        0.0
3    LBM1   DUSP6        2.428796        0.0
4    LBM1   HMGA1        1.814476        0.0

## Unfiltered

In [5]:
unfiltered_df = df.copy()
unfiltered_df.rename(columns ={"cluster": "cell_type_label"}, inplace=True)
unfiltered_df["organism"] = organism
unfiltered_df["cell_source"] = cell_source
unfiltered_df["cell_state"] = cell_state
unfiltered_df["gene_id"] = None

unfiltered_df.drop(['logfoldchanges', 'pvals_adj'], axis=1, inplace=True) 
save = unfiltered_df.to_dict(orient = "records")

## Save unfiltered

In [6]:
with open('evidence_unfiltered.json', 'w') as f:
    json.dump(save,f, indent = 4)

## Perform the filtering

In [5]:
col_pval = "pvals_adj"
col_lfc = "logfoldchanges"
col_gene = "gene"
col_ct = "cluster" # says cluster in table, but before this had "celltype"
col_rank = None # set to None if pct. 1DNE

In [6]:
min_mean = 100
max_pval = 1e-10
min_lfc = 2.2
max_gene_shares = 2
max_per_celltype = 20

# filter by pval and lfc
dfc = df.query(f"{col_pval} <= {max_pval} & {col_lfc} >= {min_lfc}")

# mask out genes that are shared between max_gene_shares cell types
non_repeat_genes = dfc[col_gene].value_counts()[dfc[col_gene].value_counts() < max_gene_shares].index.values

m = dfc[dfc[col_gene].isin(non_repeat_genes)]

if col_rank:
    m = m.sort_values(col_rank, ascending = True)

# max number to sample is equal to the min number of genes across all celltype
n_sample = min(m[col_ct].value_counts().max(), max_per_celltype)

# sample n_sample genes
markers = m.groupby(col_ct).tail(n_sample)
markers_dict = markers.groupby(col_ct)[col_gene].apply(lambda x: list(x)).to_dict()

## Check how many genes per cell type

In [7]:
markers

          cluster     gene  logfoldchanges     pvals_adj
8            LBM1   PMAIP1        2.701771  0.000000e+00
23           LBM1    VEGFD        2.299420  0.000000e+00
38           LBM1     LHX2        3.078587  0.000000e+00
64           LBM1     MYCN        2.345730  0.000000e+00
91           LBM1     MSX1        2.377080  0.000000e+00
...           ...      ...             ...           ...
4123  Endothelium  SULT1C4        3.322689  9.311667e-24
4124  Endothelium  TSPAN15        3.671395  1.090203e-23
4126  Endothelium    THSD1        4.319571  4.554218e-23
4128  Endothelium     SMTN        2.418430  5.822234e-24
4129  Endothelium    PDGFB        5.963688  2.579822e-22

[372 rows x 4 columns]

## Find Ensembl ID

In [8]:
import sys
import time

from urllib.parse import urlparse, urlencode
from urllib.request import urlopen, Request
from urllib.error import HTTPError

In [9]:
class EnsemblRestClient(object):
    def __init__(self, server='http://rest.ensembl.org', reqs_per_sec=5):
        self.server = server
        self.reqs_per_sec = reqs_per_sec
        self.req_count = 0
        self.last_req = 0

    def perform_rest_action(self, endpoint, hdrs=None, params=None):
        if hdrs is None:
            hdrs = {}

        if 'Content-Type' not in hdrs:
            hdrs['Content-Type'] = 'application/json'

        if params:
            endpoint += '?' + urlencode(params)

        data = None

        # check if we need to rate limit ourselves
        if self.req_count >= self.reqs_per_sec:
            delta = time.time() - self.last_req
            if delta < 1:
                time.sleep(1 - delta)
            self.last_req = time.time()
            self.req_count = 0
        
        try:
            request = Request(self.server + endpoint, headers=hdrs)
            response = urlopen(request)
            content = response.read()
            if content:
                data = json.loads(content)
            self.req_count += 1

        except HTTPError as e:
            # check if we are being rate limited by the server
            if e.code == 429:
                if 'Retry-After' in e.headers:
                    retry = e.headers['Retry-After']
                    time.sleep(float(retry))
                    self.perform_rest_action(endpoint, hdrs, params)
            else:
                sys.stderr.write('Request failed for {0}: Status code: {1.code} Reason: {1.reason}\n'.format(endpoint, e))
           
        return data

    def get_id(self, species, symbol):
        genes = self.perform_rest_action(
            endpoint='/xrefs/symbol/{0}/{1}'.format(species, symbol), 
            params={'object_type': 'gene'}
        )
        if genes:
            stable_id = genes[0]['id']
            return stable_id
        else:
            return "gene not found"

In [10]:
def run(symbol):
    client = EnsemblRestClient()
    gene_id = client.get_id('human', symbol)
    return gene_id

## Convert to evidence json

In [11]:
df = markers[[col_ct, col_gene]].rename(columns={col_ct : "cell_type_label", col_gene: "gene"})
df["organism"] = organism
df["cell_source"] = cell_source
df["cell_state"] = cell_state
df["gene_id"] = df["gene"]
df["gene_id"] = df["gene_id"].apply(run)
save = df.to_dict(orient = "records")

In [12]:
save

[{'cell_type_label': 'LBM1',
  'gene': 'PMAIP1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000141682'},
 {'cell_type_label': 'LBM1',
  'gene': 'VEGFD',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000165197'},
 {'cell_type_label': 'LBM1',
  'gene': 'LHX2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000106689'},
 {'cell_type_label': 'LBM1',
  'gene': 'MYCN',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000134323'},
 {'cell_type_label': 'LBM1',
  'gene': 'MSX1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000163132'},
 {'cell_type_label': 'LBM3',
  'gene': 'EMX2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000170370'},
 {'cell_type_label': 'LBM3',
  'gene': 'NR2F1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000175745'},
 {'cell_type_label': 'LBM3',
  'gene': 'IRX3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000177508'},
 {'cell_type_label': 'LBM3',
  'gene': 'HOXC6',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000197757'},
 {'cell_type_label': 'LBM3',
  'gene': 'HOXB4',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000182742'},
 {'cell_type_label': 'LBM3',
  'gene': 'EMX2OS',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000229847'},
 {'cell_type_label': 'LBM3',
  'gene': 'HOXC5',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000172789'},
 {'cell_type_label': 'LBM3',
  'gene': 'PAX1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000125813'},
 {'cell_type_label': 'LBM3',
  'gene': 'HOXB3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000120093'},
 {'cell_type_label': 'LBM3',
  'gene': 'NR2F2-AS1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000247809'},
 {'cell_type_label': 'LBM3',
  'gene': 'GLRB',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000109738'},
 {'cell_type_label': 'OCP',
  'gene': 'CRABP1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000166426'},
 {'cell_type_label': 'OCP',
  'gene': 'OSR1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000172939'},
 {'cell_type_label': 'PMSC',
  'gene': 'CSRNP1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000144655'},
 {'cell_type_label': 'PMSC',
  'gene': 'EMP1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000134531'},
 {'cell_type_label': 'PMSC',
  'gene': 'PRNP',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000171867'},
 {'cell_type_label': 'PMSC',
  'gene': 'EHD2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000024422'},
 {'cell_type_label': 'PMSC',
  'gene': 'P4HA2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000072682'},
 {'cell_type_label': 'PMSC',
  'gene': 'PCSK1N',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000102109'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'MEST',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000106484'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'FIBIN',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000176971'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'CTHRC1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000164932'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'TSPO',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000100300'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'ITM2A',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000078596'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'KLF2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000127528'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'MGP',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000111341'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'SPINT2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000167642'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'IGFBP5',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000115461'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'NR4A1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000123358'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'FMOD',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000122176'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'LMCD1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000071282'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'FOXC1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000054598'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'DHRS3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000162496'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'FXYD5',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000089327'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'CHPF',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000123989'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'TNS2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000111077'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'NR4A2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000153234'},
 {'cell_type_label': 'Chondrocyteblast',
  'gene': 'WFDC2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000101443'},
 {'cell_type_label': 'Chondrocyte',
  'gene': 'IHH',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000163501'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'NAV3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000067798'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'EYA1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000104313'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'VMO1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000182853'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'CCDC140',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000163081'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'EYA2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000064655'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'NECTIN1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000110400'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'RTN2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000125744'},
 {'cell_type_label': 'Myoprogenitor',
  'gene': 'RGS4',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000117152'},
 {'cell_type_label': 'Myocyte',
  'gene': 'PDLIM4',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000131435'},
 {'cell_type_label': 'Myocyte',
  'gene': 'EMC10',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000161671'},
 {'cell_type_label': 'Myocyte',
  'gene': 'BIN1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000136717'},
 {'cell_type_label': 'Myocyte',
  'gene': 'TNNC2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000101470'},
 {'cell_type_label': 'Myocyte',
  'gene': 'COX7A1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000161281'},
 {'cell_type_label': 'Myocyte',
  'gene': 'TNNI2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000130598'},
 {'cell_type_label': 'Myocyte',
  'gene': 'FBXL22',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000197361'},
 {'cell_type_label': 'Myocyte',
  'gene': 'DMPK',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000104936'},
 {'cell_type_label': 'Myocyte',
  'gene': 'LMOD3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000163380'},
 {'cell_type_label': 'Myocyte',
  'gene': 'ATP2B1-AS1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000271614'},
 {'cell_type_label': 'Myocyte',
  'gene': 'TMEM38A',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000072954'},
 {'cell_type_label': 'Myocyte',
  'gene': 'DOK7',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000175920'},
 {'cell_type_label': 'Myocyte',
  'gene': 'ATP2A1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000196296'},
 {'cell_type_label': 'Marophage',
  'gene': 'CTSC',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000109861'},
 {'cell_type_label': 'Marophage',
  'gene': 'RAB32',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000118508'},
 {'cell_type_label': 'Marophage',
  'gene': 'FERMT3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000149781'},
 {'cell_type_label': 'Marophage',
  'gene': 'ELF1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000130165'},
 {'cell_type_label': 'Marophage',
  'gene': 'APBB1IP',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000077420'},
 {'cell_type_label': 'Marophage',
  'gene': 'HSPA1B',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000204388'},
 {'cell_type_label': 'Marophage',
  'gene': 'RB1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000139687'},
 {'cell_type_label': 'Marophage',
  'gene': 'TACC1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000147526'},
 {'cell_type_label': 'Marophage',
  'gene': 'SYK',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000165025'},
 {'cell_type_label': 'Marophage',
  'gene': 'BIN2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000110934'},
 {'cell_type_label': 'Marophage',
  'gene': 'ABCG2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000118777'},
 {'cell_type_label': 'Marophage',
  'gene': 'DPP7',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000176978'},
 {'cell_type_label': 'Marophage',
  'gene': 'SERPINB1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000021355'},
 {'cell_type_label': 'Marophage',
  'gene': 'RAC2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000128340'},
 {'cell_type_label': 'Marophage',
  'gene': 'GATM',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000171766'},
 {'cell_type_label': 'Marophage',
  'gene': 'LAT2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000092068'},
 {'cell_type_label': 'Marophage',
  'gene': 'FCGR1A',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000150337'},
 {'cell_type_label': 'Marophage',
  'gene': 'PTPN6',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000111679'},
 {'cell_type_label': 'Marophage',
  'gene': 'PTAFR',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000169403'},
 {'cell_type_label': 'Marophage',
  'gene': 'CTSA',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000064601'},
 {'cell_type_label': 'Erythrocyte',
  'gene': 'PSTPIP2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000152229'},
 {'cell_type_label': 'Erythrocyte',
  'gene': 'FAIM2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000135472'},
 {'cell_type_label': 'Erythrocyte',
  'gene': 'SLC25A21',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000183032'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'DAG1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000173402'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'MAPK10',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000109339'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'SFN',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000175793'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'TP63',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000073282'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'CFAP57',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000243710'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'MAP7',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000135525'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'TMEM54',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000121900'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'ADGRG1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000205336'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'SH2D4A',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000104611'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'KCNG1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000026559'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'SCG5',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000166922'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'ESRP1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000104413'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'SOST',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000167941'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'ERP27',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000139055'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'RNF43',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000108375'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'GALNT7',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000109586'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'SPINT1-AS1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000261183'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'LAMA5',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000130702'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'MAL2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000147676'},
 {'cell_type_label': 'Epithelium1',
  'gene': 'RETREG1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000154153'},
 {'cell_type_label': 'Schwann',
  'gene': 'RHOB',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000143878'},
 {'cell_type_label': 'Schwann',
  'gene': 'CTNNB1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000168036'},
 {'cell_type_label': 'Schwann',
  'gene': 'SLITRK6',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000184564'},
 {'cell_type_label': 'Schwann',
  'gene': 'ARHGAP15',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000075884'},
 {'cell_type_label': 'Schwann',
  'gene': 'CD200',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000091972'},
 {'cell_type_label': 'Schwann',
  'gene': 'DNAJC1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000136770'},
 {'cell_type_label': 'Schwann',
  'gene': 'ALCAM',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000170017'},
 {'cell_type_label': 'Schwann',
  'gene': 'UBL3',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000122042'},
 {'cell_type_label': 'Schwann',
  'gene': 'SCARB2',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000138760'},
 {'cell_type_label': 'Schwann',
  'gene': 'SASH1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000111961'},
 {'cell_type_label': 'Schwann',
  'gene': 'C1orf198',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000119280'},
 {'cell_type_label': 'Schwann',
  'gene': 'TNIK',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000154310'},
 {'cell_type_label': 'Schwann',
  'gene': 'ST3GAL1',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000008513'},
 {'cell_type_label': 'Schwann',
  'gene': 'LINC01198',
  'organism': 'homo_sapiens',
  'cell_source': 'bone',
  'cell_state': None,
  'gene_id': 'ENSG00000231817'},
 {'cell_type_label': 'Schwann',
  'gene': 'SSFA2',

## Save evidence

In [13]:
with open("evidence.json", "w") as f:
    json.dump(save, f, indent = 4)